### PR TITLE
tst 111

### PR DESCRIPTION
**Pull request by quocmoet195**

### CODE REVIEW

**Comment by lelocthoVN** [comment]
Hello

**Comment by lelocthoVN** [comment]
hello em

**Comment by quocmoet195** [comment]
def copy_dataset_with_random_filenames(dataset_path):
    output_path = 'random_dataset'
    if not os.path.exists(output_path):
        os.makedirs(output_path)

    used_numbers=set()
    for root, dirs, files in os.walk(dataset_path):
        for file in files:
            while True:
                random_number = random.randint(0, 10000)
                if random_number not in used_numbers:
                    used_numbers.add(random_number)
                    break
            new_filename = f"{random_number}.jpg"
            source_file = os.path.join(root, file)
            destination_file = os.path.join(output_path, new_filename)
            shutil.copy(source_file, destination_fil

**Comment by quocmoet195** [comment]
```ruby
def prices():    if connection is None:
        connection = create_lift_pass_db_connection(connection_options)
    if request.method == 'PUT':        lift_pass_cost = request.args["cost"]
        lift_pass_type = request.args["type"]        cursor = connection.cursor()
        cursor.execute('INSERT INTO base_price (type, cost) VALUES (%s, %s) '                       'ON DUPLICATE KEY UPDATE cost = %s', (lift_pass_type, lift_pass_cost, lift_pass_cost))
        return {}
    elif request.method == 'GET':        cursor = connection.cursor()
        cursor.execute('SELECT cost FROM base_price WHERE type = %s', (request.args['type'],))        row = cursor.fetchone()
        result = {"cost": row[0]}        
        age = request.args.get('age', type=int, default=None)        is_night_pass = request.args.get('type') == 'night'
                if age and age < 6:
            return {"cost": 0}        
        if not is_night_pass:            cursor.execute('SELECT date FROM holidays')
            holidays = [row[0] for row in cursor.fetchall()]            query_date = request.args.get('date')
                        if query_date and datetime.fromisoformat(query_date).weekday() == 0:
                reduction = 35            else:
                reduction = 0            
            if age and age < 15:                result["cost"] = math.ceil(result["cost"] * 0.7)
            else:                if age is None:
                    cost = result['cost'] * (1 - reduction / 100)                    result["cost"] = math.ceil(cost)
                elif age > 64:                    cost = result['cost'] * 0.75 * (1 - reduction / 100)
                    result["cost"] = math.ceil(cost)                else:
                    cost = result['cost'] * (1 - reduction / 100)
                    result["cost"] = math.ceil(cost)        elif age and age >= 6:
            result["cost"] = math.ceil(result['cost'] * 0.4)        
        return result
```

**Pull request merged**
